### ISSUE TITLE
Crash when verifying requirements for personalized bees

### ISSUE THREAD

**Issue by bernds** [Chocohead/Binnie-Patcher#33]
Hope this is the right place to report this issue.

I'm using the FTB Crackpack, which has binnie-mods-2.0-pre14.jar and Binnie\ Patcher\ 1.8.jar.

I've noticed crashes before when using the Apiarist's Database. They seem to occur sometimes when looking at bee mutation requirements. Now I seem to have hit something more serious, occurring every time the world loads. I suspect this is due to the game trying to check requirements for a Jaded bee (I had combined Ender+Relic without realizing I couldn't actually get that bee):

23:12:14] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NoSuchMethodError: forestry.api.apiculture.IBeeHousing.getOwnerName()Lcom/mojang/authlib/GameProfile;
        at binnie.extrabees.genetics.ExtraBeeMutation$RequirementPerson.fufilled(ExtraBeeMutation.java:501) ~[ExtraBeeMutation$RequirementPerson.class:?]
        at binnie.extrabees.genetics.ExtraBeeMutation.getChance(ExtraBeeMutation.java:433) ~[ExtraBeeMutation.class:?]
        at binnie.extrabees.genetics.ExtraBeeMutation.getChance(ExtraBeeMutation.java:418) ~[ExtraBeeMutation.class:?]
        at forestry.apiculture.genetics.Bee.mutateSpecies(Bee.java:648) ~[Bee.class:?]
        at forestry.apiculture.genetics.Bee.createOffspring(Bee.java:595) ~[Bee.class:?]
        at forestry.apiculture.genetics.Bee.spawnPrincess(Bee.java:548) ~[Bee.class:?]
        at forestry.apiculture.BeekeepingLogic.spawnOffspring(BeekeepingLogic.java:397) ~[BeekeepingLogic.class:?]
        at forestry.apiculture.BeekeepingLogic.killQueen(BeekeepingLogic.java:363) ~[BeekeepingLogic.class:?]
        at forestry.apiculture.BeekeepingLogic.canWork(BeekeepingLogic.java:184) ~[BeekeepingLogic.class:?]
        at forestry.apiculture.tiles.TileBeeHousingBase.updateServerSide(TileBeeHousingBase.java:122) ~[TileBeeHousingBase.class:?]
        at forestry.core.tiles.TileForestry.func_145845_h(TileForestry.java:118) ~[TileForestry.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]

I made some attempts at decompiling/fixing/recompiling the ExtraBees code but couldn't get the compilation to work. Is this something that could be fixed with BinniePatcher?

**Comment by Chocohead** [comment]
It's probably just a missed fix, Binnie Patcher fixes (or at least aims to fix) all of the `IBeeHousing` implementations.

**Comment by Scrik** [comment]
similar crash, http://pastebin.com/iAS5SZcm
please fix
P.S. when entering the server, a server crash

**Comment by Chocohead** [comment]
I did indeed miss the class, fixed next version.

**Comment by bernds** [comment]
Pardon me if I missed it, but is that new version available for download anywhere yet?

**Comment by KorDum** [comment]
BinniePatcher no longer need. Check new versions of Binnie.
